name: 'Composite action (Get & Cache Dependencies)'
description: 'A composite action that gets and caches dependencies'
runs:
  using: 'composite'
  steps:
    - name: Cache Dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: cd client && npm ci
      shell: bash
