name: Demo file
on: 
    pull_request:
    workflow_dispatch:
  
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Uses Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'
      - name: Install Dependencies
        run: npm ci
      - name: Test cases
        run: npm test
  checkLint:
    needs: test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Linting
        run: npm lint
  deploy:
    needs: checkLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm build
      - name: Deploy
        run: echo "Deploying!"