name: Demo file
on: 
    pull_request:
    workflow_dispatch:
  
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Uses Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'
      - name: Install Dependencies
        run: npm ci
      - name: Test cases
        run: npm test
  checkLint:
    needs: test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Linting
        run: npm run lint
  deploy:
    needs: checkLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: echo "Deploying!"
  upload-artifact:
    needs: checkLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build Artifact
        run: npm run build
      - name: Publish file name
        run: find build/assets/*.js -type f -execdir echo '{}' ';'
      - name: Get Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build
  download-artifact:
      needs: "upload-artifact"
      runs-on: ubuntu-latest
      steps:
        - name: Get Download Artifact
          uses: actions/download-artifact@v3
          with:
            name: build-artifacts
