name: Issues Holding Action
on: push
  branches: [ "main" ]
  jobs:
    issues:
      runs-on: ubuntu-latest
      steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Output context details
        run: echo "The issue is ${{ github.event.issue.number }} and the action is ${{ github.event_name }}"
