name: First push to main workflow
on: 
  pull_request:
    branches: [ "main1" ]
  
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print greeting
      run:  echo 'Hello world!'
    - name: Print goodbye
      run: |
        echo 'Done 1  -  bye!'
        echo 'Done  -  bye!'
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - run: npm run build --if-present
    