name: Demo file
on: 
  push:
    branches: ["main", "workflow"]
env:
  MONGODB_CONNECTION_PROTOCOL: mongodb #mongodb+srv
  MONGODB_CLUSTER_ADDRESS: mongodb #cluster0.s3wa7.mongodb.net/
  MONGODB_USERNAME: ${{ secrets.MONGODDB_USERNAME }} # dummyBff@admin
  MONGODB_PASSWORD: ${{ secrets.MONGODDB_PASSWORD }} # 8010258023
  PORT: 8081
jobs: 
  test:
    container: 
      image: node:20
    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGODDB_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGODDB_PASSWORD }}
        ports: 
          - 27017:27017
        options: --name mongo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Uses Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'
      - name: Install Dependencies
        run: cd client && npm ci
      - name: run server
        run: cd client && npm start & npx wait-on http://localhost:${{ env.PORT }}
      - name: Test cases
        run: cd client && npm test
  checkLint:
    needs: test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: cd client && npm ci
      - name: Checking Linting
        run: cd client && npm run lint
  deploy:
    needs: checkLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: cd client && npm ci
      - name: Build
        run: cd client && npm run build
      - name: Deploy
        run: echo "Deploying! ${{ env.MONGODB_USERNAME }}"
